// AUTO-GENERATED by scripts/extract/extract-curvetables.ts — do not edit.
// Regenerate: bun run extract --only curvetables
import type { CurveFile } from '@/types/curves';
import tier1 from './health_universal_tier1.json';
import tier2 from './health_universal_tier2.json';
import tier3 from './health_universal_tier3.json';
import tier4 from './health_universal_tier4.json';
import tier5 from './health_universal_tier5.json';
import tier6 from './health_universal_tier6.json';
import tier7 from './health_universal_tier7.json';
import tier8 from './health_universal_tier8.json';
import tier9 from './health_universal_tier9.json';
import tier10 from './health_universal_tier10.json';
import tier11 from './health_universal_tier11.json';
import tier12 from './health_universal_tier12.json';
import tier13 from './health_universal_tier13.json';
import tier14 from './health_universal_tier14.json';
import tier15 from './health_universal_tier15.json';
import tier16 from './health_universal_tier16.json';
import tier17 from './health_universal_tier17.json';
import tier18 from './health_universal_tier18.json';
import tier19 from './health_universal_tier19.json';
import tier20 from './health_universal_tier20.json';
import tier21 from './health_universal_tier21.json';
import tier22 from './health_universal_tier22.json';
import tier23 from './health_universal_tier23.json';
import tier24 from './health_universal_tier24.json';
import tier25 from './health_universal_tier25.json';
import tier26 from './health_universal_tier26.json';
import tier27 from './health_universal_tier27.json';
import tier28 from './health_universal_tier28.json';
import tier29 from './health_universal_tier29.json';
import tier30 from './health_universal_tier30.json';
import tier31 from './health_universal_tier31.json';
import tier32 from './health_universal_tier32.json';
import tier33 from './health_universal_tier33.json';
import tier34 from './health_universal_tier34.json';
import tier35 from './health_universal_tier35.json';
import tier36 from './health_universal_tier36.json';
import tier37 from './health_universal_tier37.json';
import tier38 from './health_universal_tier38.json';
import tier39 from './health_universal_tier39.json';
import tier40 from './health_universal_tier40.json';
import tier41 from './health_universal_tier41.json';
import tier42 from './health_universal_tier42.json';
import tier43 from './health_universal_tier43.json';
import tier44 from './health_universal_tier44.json';
import tier45 from './health_universal_tier45.json';
import tier46 from './health_universal_tier46.json';
import tier47 from './health_universal_tier47.json';
import tier48 from './health_universal_tier48.json';
import tier49 from './health_universal_tier49.json';
import tier50 from './health_universal_tier50.json';
import tier51 from './health_universal_tier51.json';
import tier52 from './health_universal_tier52.json';
import tier53 from './health_universal_tier53.json';
import tier54 from './health_universal_tier54.json';
import tier55 from './health_universal_tier55.json';
import tier56 from './health_universal_tier56.json';
import tier57 from './health_universal_tier57.json';
import tier58 from './health_universal_tier58.json';
import tier59 from './health_universal_tier59.json';
import tier60 from './health_universal_tier60.json';

export default {
  1: tier1,
  2: tier2,
  3: tier3,
  4: tier4,
  5: tier5,
  6: tier6,
  7: tier7,
  8: tier8,
  9: tier9,
  10: tier10,
  11: tier11,
  12: tier12,
  13: tier13,
  14: tier14,
  15: tier15,
  16: tier16,
  17: tier17,
  18: tier18,
  19: tier19,
  20: tier20,
  21: tier21,
  22: tier22,
  23: tier23,
  24: tier24,
  25: tier25,
  26: tier26,
  27: tier27,
  28: tier28,
  29: tier29,
  30: tier30,
  31: tier31,
  32: tier32,
  33: tier33,
  34: tier34,
  35: tier35,
  36: tier36,
  37: tier37,
  38: tier38,
  39: tier39,
  40: tier40,
  41: tier41,
  42: tier42,
  43: tier43,
  44: tier44,
  45: tier45,
  46: tier46,
  47: tier47,
  48: tier48,
  49: tier49,
  50: tier50,
  51: tier51,
  52: tier52,
  53: tier53,
  54: tier54,
  55: tier55,
  56: tier56,
  57: tier57,
  58: tier58,
  59: tier59,
  60: tier60,
} as Record<number, CurveFile>;