// AUTO-GENERATED by scripts/extract/extract-curvetables.ts — do not edit.
// Regenerate: bun run extract --only curvetables
import type { CurveFile } from '@/types/curves';
import tier1 from './damage_universal_tier1.json';
import tier2 from './damage_universal_tier2.json';
import tier3 from './damage_universal_tier3.json';
import tier4 from './damage_universal_tier4.json';
import tier5 from './damage_universal_tier5.json';
import tier6 from './damage_universal_tier6.json';
import tier7 from './damage_universal_tier7.json';
import tier8 from './damage_universal_tier8.json';
import tier9 from './damage_universal_tier9.json';
import tier10 from './damage_universal_tier10.json';
import tier11 from './damage_universal_tier11.json';
import tier12 from './damage_universal_tier12.json';
import tier13 from './damage_universal_tier13.json';
import tier14 from './damage_universal_tier14.json';
import tier15 from './damage_universal_tier15.json';
import tier16 from './damage_universal_tier16.json';
import tier17 from './damage_universal_tier17.json';
import tier18 from './damage_universal_tier18.json';
import tier19 from './damage_universal_tier19.json';
import tier20 from './damage_universal_tier20.json';
import tier21 from './damage_universal_tier21.json';
import tier22 from './damage_universal_tier22.json';
import tier23 from './damage_universal_tier23.json';
import tier24 from './damage_universal_tier24.json';
import tier25 from './damage_universal_tier25.json';
import tier26 from './damage_universal_tier26.json';
import tier27 from './damage_universal_tier27.json';
import tier28 from './damage_universal_tier28.json';
import tier29 from './damage_universal_tier29.json';
import tier30 from './damage_universal_tier30.json';
import tier31 from './damage_universal_tier31.json';
import tier32 from './damage_universal_tier32.json';
import tier33 from './damage_universal_tier33.json';
import tier34 from './damage_universal_tier34.json';
import tier35 from './damage_universal_tier35.json';
import tier36 from './damage_universal_tier36.json';
import tier37 from './damage_universal_tier37.json';
import tier38 from './damage_universal_tier38.json';
import tier39 from './damage_universal_tier39.json';
import tier40 from './damage_universal_tier40.json';
import tier41 from './damage_universal_tier41.json';
import tier42 from './damage_universal_tier42.json';
import tier43 from './damage_universal_tier43.json';
import tier44 from './damage_universal_tier44.json';
import tier45 from './damage_universal_tier45.json';
import tier46 from './damage_universal_tier46.json';
import tier47 from './damage_universal_tier47.json';
import tier48 from './damage_universal_tier48.json';
import tier49 from './damage_universal_tier49.json';
import tier50 from './damage_universal_tier50.json';
import tier51 from './damage_universal_tier51.json';
import tier52 from './damage_universal_tier52.json';
import tier53 from './damage_universal_tier53.json';
import tier54 from './damage_universal_tier54.json';
import tier55 from './damage_universal_tier55.json';
import tier56 from './damage_universal_tier56.json';
import tier57 from './damage_universal_tier57.json';
import tier58 from './damage_universal_tier58.json';
import tier59 from './damage_universal_tier59.json';
import tier60 from './damage_universal_tier60.json';
import tier61 from './damage_universal_tier61.json';
import tier62 from './damage_universal_tier62.json';
import tier63 from './damage_universal_tier63.json';
import tier64 from './damage_universal_tier64.json';
import tier65 from './damage_universal_tier65.json';
import tier66 from './damage_universal_tier66.json';
import tier67 from './damage_universal_tier67.json';
import tier68 from './damage_universal_tier68.json';
import tier69 from './damage_universal_tier69.json';
import tier70 from './damage_universal_tier70.json';
import tier71 from './damage_universal_tier71.json';
import tier72 from './damage_universal_tier72.json';
import tier73 from './damage_universal_tier73.json';
import tier74 from './damage_universal_tier74.json';
import tier75 from './damage_universal_tier75.json';
import tier76 from './damage_universal_tier76.json';
import tier77 from './damage_universal_tier77.json';
import tier78 from './damage_universal_tier78.json';
import tier79 from './damage_universal_tier79.json';
import tier80 from './damage_universal_tier80.json';
import tier81 from './damage_universal_tier81.json';
import tier82 from './damage_universal_tier82.json';
import tier83 from './damage_universal_tier83.json';
import tier84 from './damage_universal_tier84.json';
import tier85 from './damage_universal_tier85.json';
import tier86 from './damage_universal_tier86.json';
import tier87 from './damage_universal_tier87.json';
import tier88 from './damage_universal_tier88.json';
import tier89 from './damage_universal_tier89.json';
import tier90 from './damage_universal_tier90.json';
import tier91 from './damage_universal_tier91.json';
import tier92 from './damage_universal_tier92.json';
import tier93 from './damage_universal_tier93.json';
import tier94 from './damage_universal_tier94.json';
import tier95 from './damage_universal_tier95.json';
import tier96 from './damage_universal_tier96.json';
import tier97 from './damage_universal_tier97.json';
import tier98 from './damage_universal_tier98.json';
import tier99 from './damage_universal_tier99.json';
import tier100 from './damage_universal_tier100.json';

export default {
  1: tier1,
  2: tier2,
  3: tier3,
  4: tier4,
  5: tier5,
  6: tier6,
  7: tier7,
  8: tier8,
  9: tier9,
  10: tier10,
  11: tier11,
  12: tier12,
  13: tier13,
  14: tier14,
  15: tier15,
  16: tier16,
  17: tier17,
  18: tier18,
  19: tier19,
  20: tier20,
  21: tier21,
  22: tier22,
  23: tier23,
  24: tier24,
  25: tier25,
  26: tier26,
  27: tier27,
  28: tier28,
  29: tier29,
  30: tier30,
  31: tier31,
  32: tier32,
  33: tier33,
  34: tier34,
  35: tier35,
  36: tier36,
  37: tier37,
  38: tier38,
  39: tier39,
  40: tier40,
  41: tier41,
  42: tier42,
  43: tier43,
  44: tier44,
  45: tier45,
  46: tier46,
  47: tier47,
  48: tier48,
  49: tier49,
  50: tier50,
  51: tier51,
  52: tier52,
  53: tier53,
  54: tier54,
  55: tier55,
  56: tier56,
  57: tier57,
  58: tier58,
  59: tier59,
  60: tier60,
  61: tier61,
  62: tier62,
  63: tier63,
  64: tier64,
  65: tier65,
  66: tier66,
  67: tier67,
  68: tier68,
  69: tier69,
  70: tier70,
  71: tier71,
  72: tier72,
  73: tier73,
  74: tier74,
  75: tier75,
  76: tier76,
  77: tier77,
  78: tier78,
  79: tier79,
  80: tier80,
  81: tier81,
  82: tier82,
  83: tier83,
  84: tier84,
  85: tier85,
  86: tier86,
  87: tier87,
  88: tier88,
  89: tier89,
  90: tier90,
  91: tier91,
  92: tier92,
  93: tier93,
  94: tier94,
  95: tier95,
  96: tier96,
  97: tier97,
  98: tier98,
  99: tier99,
  100: tier100,
} as Record<number, CurveFile>;